apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:

  name: testom

  namespace: mongodb

spec:

  replicas: 1

  version: 4.2.3

  adminCredentials: mongodb-pass # Should match metadata.name

                                           # in the Kubernetes secret

                                           # for the admin user
  
  applicationDatabase:

    members: 3

    version: 4.2.0

    persistent: false 
